-- Migration: Create AI News Insights Gold Table
-- Run this to create the table structure before first use

CREATE SCHEMA IF NOT EXISTS gold;

CREATE TABLE IF NOT EXISTS pg_vault.gold.fact_ai_news_insights (
    news_hkey VARCHAR(32) NOT NULL,
    source_domain VARCHAR(500),
    source_url TEXT,
    event_datetime TIMESTAMP,
    category VARCHAR(50) NOT NULL,  -- 'top_negative', 'top_positive', 'most_polarizing'
    continent VARCHAR(50),
    country_name VARCHAR(100),
    tone_overall DOUBLE PRECISION,
    tone_positive DOUBLE PRECISION,
    tone_negative DOUBLE PRECISION,
    tone_polarity DOUBLE PRECISION,
    report_count INTEGER,
    ai_abstract TEXT,  -- AI-generated summary (max 40 words)
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Primary key on news + category (same news can appear in multiple categories)
    PRIMARY KEY (news_hkey, category)
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_ai_insights_category 
    ON pg_vault.gold.fact_ai_news_insights(category);

CREATE INDEX IF NOT EXISTS idx_ai_insights_continent 
    ON pg_vault.gold.fact_ai_news_insights(continent);

CREATE INDEX IF NOT EXISTS idx_ai_insights_generated 
    ON pg_vault.gold.fact_ai_news_insights(generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_insights_tone 
    ON pg_vault.gold.fact_ai_news_insights(tone_overall);

-- Add comment
COMMENT ON TABLE pg_vault.gold.fact_ai_news_insights IS 
'AI-generated insights for top sentiment news articles. Populated by ai_news_insights.py script.';

COMMENT ON COLUMN pg_vault.gold.fact_ai_news_insights.ai_abstract IS 
'AI-generated summary of article content, limited to 40 words. Generated by Ollama (Llama 3.2).';

-- Show success
SELECT 'Table pg_vault.gold.fact_ai_news_insights created successfully' AS status;
